# -*- coding: utf-8 -*-
"""Copy of Google Trends.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zkfuEZhf7aCzWmX5RufD4PK3rWNsTpbY
"""

import pandas as pd
import pytrends
from pytrends.request import TrendReq
from datetime import datetime
import seaborn as sns

pip install pytrends

pytrend = TrendReq()

# %%

FINANCIALS_KEYWORDS = ['Banks', 'Regulations', "Inflation", 'Stock Market', 'Bonds', 'Equities', 'Finance', 'Financial Technology']
TECHS_KEYWORDS = ['Technology', 'Information Technology', 'Tech']

FINANCIALS_KEYWORDS_CODES=[pytrend.suggestions(keyword=i)[0] for i in FINANCIALS_KEYWORDS]
TECHS_KEYWORDS_CODES=[pytrend.suggestions(keyword=i)[0] for i in TECHS_KEYWORDS]

df_FINANCIALS_CODES= pd.DataFrame(FINANCIALS_KEYWORDS_CODES)
df_TECHS_CODES= pd.DataFrame(TECHS_KEYWORDS_CODES)

print(df_FINANCIALS_CODES)
print(df_TECHS_CODES)


# %%

FINANCIALS_EXACT_KEYWORDS=df_FINANCIALS_CODES['mid'].to_list()
TECH_EXACT_KEYWORDS=df_TECHS_CODES['mid'].to_list()

# TODAYS_DATE = datetime.today().strftime('%Y-%m-%d')


DATE_INTERVAL='2020-01-01 2020-05-01' # this should be dynamic
COUNTRY=["US"] # https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
CATEGORY=0 # https://github.com/pat310/google-trends-api/wiki/Google-Trends-Categories
SEARCH_TYPE='' #default is 'web searches',others include 'images','news','youtube','froogle' (google shopping)

# %%

Individual_FINANCIALS_EXACT_KEYWORD = list(zip(*[iter(FINANCIALS_EXACT_KEYWORDS)]*1))
Individual_FINANCIALS_EXACT_KEYWORD = [list(x) for x in Individual_FINANCIALS_EXACT_KEYWORD]

Individual_TECHS_EXACT_KEYWORD = list(zip(*[iter(TECH_EXACT_KEYWORDS)]*1))
Individual_TECHS_EXACT_KEYWORD = [list(x) for x in Individual_TECHS_EXACT_KEYWORD]

# %%
dicti_FINANCIALS = {}
dicti_TECHS = {}

i = 1
for Country in COUNTRY:
    for keyword in Individual_FINANCIALS_EXACT_KEYWORD:
        pytrend.build_payload(kw_list=keyword,
                              timeframe = DATE_INTERVAL,
                              geo = Country,
                              cat=CATEGORY,
                              gprop=SEARCH_TYPE)
        dicti_FINANCIALS[i] = pytrend.interest_over_time()
        i+=1
df_trends_FINANCIALS = pd.concat(dicti_FINANCIALS, axis=1)


j = 1
for Country in COUNTRY:
    for keyword in Individual_TECHS_EXACT_KEYWORD:
        pytrend.build_payload(kw_list=keyword,
                              timeframe = DATE_INTERVAL,
                              geo = Country,
                              cat=CATEGORY,
                              gprop=SEARCH_TYPE)
        dicti_TECHS[j] = pytrend.interest_over_time()
        j+=1
df_trends_TECHS = pd.concat(dicti_TECHS, axis=1)
# %%

df_trends_FINANCIALS.columns = df_trends_FINANCIALS.columns.droplevel(0) #drop outside header
df_trends_FINANCIALS = df_trends_FINANCIALS.drop('isPartial', axis = 1) #drop "isPartial"
df_trends_FINANCIALS.reset_index(level=0,inplace=True) #reset_index
df_trends_FINANCIALS.columns=['date'] + FINANCIALS_KEYWORDS #change column names

df_trends_TECHS.columns = df_trends_TECHS.columns.droplevel(0) #drop outside header
df_trends_TECHS = df_trends_TECHS.drop('isPartial', axis = 1) #drop "isPartial"
df_trends_TECHS.reset_index(level=0,inplace=True) #reset_index
df_trends_TECHS.columns=['date'] + TECHS_KEYWORDS #change column names

# %%

# Viz
import seaborn as sns
sns.set(color_codes=True)

dx = df_trends_FINANCIALS.plot(figsize = (12,8),x="date", y=FINANCIALS_KEYWORDS, kind="line", title = "FINANCIALS")
dx.set_xlabel('Date')
dx.set_ylabel('Trends Index')
dx.tick_params(axis='both', which='both', labelsize=10)

dx = df_trends_TECHS.plot(figsize = (12,8),x="date", y=TECHS_KEYWORDS, kind="line", title = "TECHS")
dx.set_xlabel('Date')
dx.set_ylabel('Trends Index')
dx.tick_params(axis='both', which='both', labelsize=10)

#keywords should be list with string inputs
#date interval should be a string of the form: "YYYY-MM-DD YYYY-MM-DD" where the left date is the start date and the right date is the end date
def googletrends(keywords, date_interval):
  pytrend = TrendReq()
  keywords_codes = [pytrend.suggestions(keyword=i)[0] for i in keywords]
  df_keywords_codes= pd.DataFrame(keywords_codes)
  exact_keywords=df_keywords_codes['mid'].to_list()


  DATE_INTERVAL=date_interval # this should be dynamic
  COUNTRY=["US"] # https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
  CATEGORY=0 # https://github.com/pat310/google-trends-api/wiki/Google-Trends-Categories
  SEARCH_TYPE='' #default is 'web searches',others include 'images','news','youtube','froogle' (google shopping)

  individual_exact_keywords = list(zip(*[iter(exact_keywords)]*1))
  individual_exact_keywords = [list(x) for x in individual_exact_keywords]

  dicti = {}

  i = 1
  for Country in COUNTRY:
    for keyword in individual_exact_keywords:
        pytrend.build_payload(kw_list=keyword,
                              timeframe = DATE_INTERVAL,
                              geo = Country,
                              cat=CATEGORY,
                              gprop=SEARCH_TYPE)
        dicti[i] = pytrend.interest_over_time()
        i+=1
  df_trends = pd.concat(dicti, axis=1)


  df_trends.columns = df_trends.columns.droplevel(0) #drop outside header
  df_trends = df_trends.drop('isPartial', axis = 1) #drop "isPartial"
  df_trends.reset_index(level=0,inplace=True) #reset_index
  df_trends.columns=['date'] + keywords #change column names

  # Viz

  sns.set(color_codes=True)

  dx = df_trends.plot(figsize = (12,8),x="date", y=keywords, kind="line", title = "Trends")
  dx.set_xlabel('Date')
  dx.set_ylabel('Trends Index')
  dx.tick_params(axis='both', which='both', labelsize=10)
  return df_trends

df = googletrends(['Finance', 'Inflation'], '2021-06-01 2021-07-01')
df